const { Table } = require("../src/table.js");

// Table structure for tb_system
let data = '[{"field":{"id": 13, "mask": "", "name": "id", "size": 0, "id_fk": 0, "label": "Id", "domain": "", "id_table": 2, "id_system": 1, "id_unique": "Y", "field_type": "integer", "id_mandatory": "Y"}}, {"field":{"id": 14, "mask": "", "name": "name", "size": 50, "id_fk": 0, "label": "Name", "domain": "", "id_table": 2, "id_system": 1, "id_unique": "N", "field_type": "string", "id_mandatory": "Y"}}, {"field":{"id": 15, "mask": "", "name": "id_parent", "size": 0, "id_fk": 2, "label": "Parent", "domain": "", "id_table": 2, "id_system": 1, "id_unique": "N", "field_type": "integer", "id_mandatory": "Y"}}, {"field":{"id": 16, "mask": "", "name": "url", "size": 50, "id_fk": 0, "label": "Url", "domain": "", "id_table": 2, "id_system": 1, "id_unique": "N", "field_type": "string", "id_mandatory": "Y"}}]';
let struct = '[{"id":22,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"id","field_label":"Id","field_type":"integer","field_size":0,"field_mask":"","field_fk":0,"id_mandatory":"Y","id_unique":"Y","domain_name":""}, {"id":23,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"id_table","field_label":"Tabela","field_type":"integer","field_size":0,"field_mask":"","field_fk":3,"id_mandatory":"Y","id_unique":"N","domain_name":""}, {"id":24,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"label","field_label":"Label","field_type":"string","field_size":50,"field_mask":"","field_fk":0,"id_mandatory":"Y","id_unique":"N","domain_name":""}, {"id":25,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"name","field_label":"Nome","field_type":"string","field_size":50,"field_mask":"","field_fk":0,"id_mandatory":"Y","id_unique":"N","domain_name":""}, {"id":26,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"field_type","field_label":"Tipo do Campo","field_type":"string","field_size":0,"field_mask":"","field_fk":5,"id_mandatory":"Y","id_unique":"N","domain_name":"tb_field_type"}, {"id":27,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"size","field_label":"Tamanho","field_type":"integer","field_size":0,"field_mask":"","field_fk":0,"id_mandatory":"N","id_unique":"N","domain_name":""}, {"id":28,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"mask","field_label":"Mascara","field_type":"string","field_size":50,"field_mask":"","field_fk":0,"id_mandatory":"N","id_unique":"N","domain_name":""}, {"id":29,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"id_mandatory","field_label":"Obrigatório","field_type":"boolean","field_size":0,"field_mask":"","field_fk":5,"id_mandatory":"N","id_unique":"N","domain_name":"tb_bool"}, {"id":30,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"id_unique","field_label":"Unico","field_type":"boolean","field_size":0,"field_mask":"","field_fk":5,"id_mandatory":"N","id_unique":"N","domain_name":"tb_bool"}, {"id":31,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"id_fk","field_label":"Tabela","field_type":"integer","field_size":0,"field_mask":"","field_fk":3,"id_mandatory":"N","id_unique":"N","domain_name":""}, {"id":32,"id_system":1,"id_table":4,"table_name":"tb_field","field_name":"domain","field_label":"Domínio","field_type":"string","field_size":50,"field_mask":"","field_fk":0,"id_mandatory":"N","id_unique":"N","domain_name":""}]';

let table = new Table(struct, data);

console.log(table.ola());

console.log(table.createTable())